// <auto-generated />
using Aplikacja_kulinarna.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Aplikacja_kulinarna.Migrations
{
    [DbContext(typeof(CulinaryContext))]
    [Migration("20180728124333_SeedRecipes")]
    partial class SeedRecipes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846");

            modelBuilder.Entity("Aplikacja_kulinarna.Models.Recipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Dish");

                    b.Property<string>("DishRecipe")
                        .HasMaxLength(2000);

                    b.Property<int>("MinutesToPrepare");

                    b.Property<int>("QualityStars");

                    b.HasKey("RecipeId");

                    b.ToTable("Recipes");

                    b.HasData(
                        new { RecipeId = 1, Dish = "Chips", DishRecipe = "Peel potatoes. Cut them into thin, long sticks. Fry them.", MinutesToPrepare = 10, QualityStars = 1 },
                        new { RecipeId = 2, Dish = "Fish and chips", DishRecipe = "Prepare chips. Fry fish. Serve together", MinutesToPrepare = 20, QualityStars = 2 },
                        new { RecipeId = 3, Dish = "Ham sandwich", DishRecipe = "Slice bread. Put butter on its top. Add ham.", MinutesToPrepare = 7, QualityStars = 3 }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
