// <auto-generated />
using Aplikacja_kulinarna.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Aplikacja_kulinarna.Migrations
{
    [DbContext(typeof(CulinaryContext))]
    [Migration("20180725200617_SeedRecipes")]
    partial class SeedRecipes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846");

            modelBuilder.Entity("Aplikacja_kulinarna.Models.Recipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Dish");

                    b.Property<string>("DishRecipe")
                        .HasMaxLength(2000);

                    b.Property<int>("MinutesToPrepare");

                    b.Property<int>("QualityStars");

                    b.HasKey("RecipeId");

                    b.ToTable("Recipe");

                    b.HasData(
                        new { RecipeId = 1, Dish = "Tea", DishRecipe = "Boil water and add tea", MinutesToPrepare = 3, QualityStars = 1 },
                        new { RecipeId = 2, Dish = "Coffe", DishRecipe = "Boil water. Add coffe and sugar", MinutesToPrepare = 5, QualityStars = 2 },
                        new { RecipeId = 3, Dish = "Caffe Latte", DishRecipe = "Boil water. Add coffe. Add milk. Add sugar", MinutesToPrepare = 7, QualityStars = 3 }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
